---
title: "MCRI Palettes"
output:
  html_document:
    keep_md: true
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  fig.path = "figure/",
  fig.height = 1
)
```

Colour palettes based on the MCRI branding.

Most of the code is taken from [Karthik Ram's `wesanderson` 
palette](https://github.com/karthik/wesanderson)

# Installation

```R
devtools::install_github("lazappi/mcriPalettes")
```

# Palettes

```{r, palettes_dummy}
library("mcriPalettes")

# See all palettes
pal.names <- names(mcri.palettes)
pal.names

library("ggplot2")

gg <- ggplot(iris, aes(Sepal.Length, Sepal.Width, color = Species)) + 
      geom_point(size = 3)
```

## Symbol

```{r, symbol, fig.height = 3}
mcriPalette("symbol")
gg + scale_color_manual(values = mcriPalette("symbol"))
```

## Greys

```{r, greys, fig.height = 3}
mcriPalette("greys")
gg + scale_color_manual(values = mcriPalette("greys"))
```

# Old palettes

## Themes

```{r, themes, fig.height = 3}
mcriPalette("themes")
gg + scale_color_manual(values = mcriPalette("themes"))
```

## Themes - Mid

```{r, themes-mid, fig.height = 3}
mcriPalette("themesMid")
gg + scale_color_manual(values = mcriPalette("themesMid"))
```

## Themes - Lite

```{r, themes-lite, fig.height = 3}
mcriPalette("themesLite")
gg + scale_color_manual(values = mcriPalette("themesLite"))
```

## Themes - Paired

```{r, themes-paired, fig.height = 3}
mcriPalette("themesPaired")
gg + scale_color_manual(values = mcriPalette("themesPaired"))
```

## Themes - Tripled

```{r, themes-tripled, fig.height = 3}
mcriPalette("themesTripled")
gg + scale_color_manual(values = mcriPalette("themesTripled"))
```

## Blues

```{r, blues, fig.height = 3}
mcriPalette("blues")
gg + scale_color_manual(values = mcriPalette("blues"))
```

## Blues - Mid

```{r, blues-mid, fig.height = 3}
mcriPalette("bluesMid")
gg + scale_color_manual(values = mcriPalette("bluesMid"))
```

## Blues - Lite

```{r, blues-lite, fig.height = 3}
mcriPalette("bluesLite")
gg + scale_color_manual(values = mcriPalette("bluesLite"))
```

## Blues - Paired

```{r, blues-paired, fig.height = 3}
mcriPalette("bluesPaired")
gg + scale_color_manual(values = mcriPalette("bluesPaired"))
```

## Blues - Tripled

```{r, blues-tripled, fig.height = 3}
mcriPalette("bluesTripled")
gg + scale_color_manual(values = mcriPalette("bluesTripled"))
```

## Logo

```{r, logo, fig.height = 3}
mcriPalette("logo")
gg + scale_color_manual(values = mcriPalette("logo"))
```